name: 'get_scripts'
description: 'Partially checkout CI files onto build dir'
inputs:
  branch:
    description: 'Branch'
    required: false
    default: 'master'
  repo:
    description: 'Repo'
    required: false
    default: 'https://github.com/libbpf/ci'
  files:
    description: 'Files to copy separated with space'
    required: false
    default: 'custom-workflows travis-ci'
  destdir:
    description: 'Destination of checkout'
    required: false
    default: './'
runs:
  using: "composite"
  steps:
    - name: Clone
      run: |
         # using nested actions not implemented https://github.com/actions/runner/pull/612
         # so just plaint git clone
         git clone -b ${{ inputs.branch }} ${{ inputs.repo }} /tmp/_temp_get_scripts
      shell: bash
    - name: Copy files
      run: |
        for f in ${{ inputs.files }};
          do cp -a /tmp/_temp_get_scripts/$f ${{ inputs.destdir }}
        done
        rm -rf /tmp/_temp_get_scripts
      shell: bash
