sudo: required
language: bash
dist: bionic
services:
- docker
env:
  global:
  - PROJECT_NAME='libbpf'
  - AUTHOR_EMAIL="$(git log -1 --pretty=\"%aE\")"
  - REPO_ROOT="$TRAVIS_BUILD_DIR"
  - CI_ROOT="$REPO_ROOT/travis-ci"
  - VMTEST_ROOT="$CI_ROOT/vmtest"
  - secure: "wlcELYaobpjU0CfVYahRltEt1sK53plocu/UvEjJAYo0Sr5uygAbLWue7UgH17izMKz1czWot9FYeCo14zcBI1Z2V419JkF1o3a2o/PvrsZM6ljTjJvenAdDBrHjlxj+11n9dLbIOjHvKyJvCG62cI+bBZfornGxHLonb08FrXZGcw46W6L/fvNJXG9BDa6/tCtAEpW7hs0qDAuROPF8aGgF9DADIYPMvY1Pp4AfKWauHpvUnDGGOKb/VnnkUdtEsIZ3Fddvbh3t4e4fJFMsr/z2kSPAJ/KmaR5/bGKmKnDlND9SUPFVxYw1Wt79CM4cEE4iFsAEFBIzKva2f3ynP4ayzottQ2vnKwxS1/MWW3fmofNdXc/f6+pWEDbxw/NZTomoM4hdxALw3C97yZWkiIQWwxebsNYoKkTYHSjoagLfRnxwGI8eaRmvqR3nUF5C8Zy6LIjS6RehULXrvVh714T94hEev62NB4GwG11eBHBJaKO/HuLspqEO+yMa6cd2HmQ4DGh8QnELNNG0kiBv7oMkJaygpqkTnLYPbQL3eId8lQspt3X/1tcp9FKdBglvlVzh3zWctUXY6xcFpvSqJMvKDatHZqIQO6Z1T1iW4CGt0WjYvxoILiMF+cmiGrWaFwOUFET+lisxxzaav7ft/UAkmN+/q8uOeqlSLGW92Hg="
addons:
  apt:
    packages:
    - qemu-kvm
    - zstd
    - binutils-dev
    - elfutils
    - libcap-dev
    - libelf-dev
    - libdw-dev
    - python3-docutils
    - python3-pip
    - python3-setuptools
    - python3-dev
    - python3-wheel
jobs:
  include:
  - stage: Builds & Tests
    name: Kernel LATEST + selftests
    language: bash
    env: KERNEL=LATEST
    script: "echo TEST > $CI_ROOT/vmtest/report && false"
    after_failure: "pip3 install -r $CI_ROOT/github/requirements.txt && cat $CI_ROOT/vmtest/report | $CI_ROOT/github/gh.py comment"
